version: '3'
services:
  mongo:
    image: mongo:4.0.10
    ports:
      - 57017:27017
  polling_app:
    build: .
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      host: mongo
      port: 51017
      database: polling-app
