version: '1'
services:
  mongo:
    image: mongo:4.0.10
    ports:
      - 27017
  otus_library:
    build: .
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/polling-app"