spring:
  data:
    mongodb:
      host: ${host:localhost}
      port: ${port:27017}
      database: ${database:polling-app}

logging:
  file: "tmp_log.log"
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
